#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/data/data/com.termux/files/usr/lib/code-oss/code-oss" "/data/data/com.termux/files/home/.config/Code - OSS/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"